# Generated by Django 4.0.5 on 2022-09-25 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='issued_books',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BookApp.book'),
        ),
    ]
