# Generated by Django 4.0.5 on 2022-09-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0002_alter_user_issued_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='page',
        ),
    ]
