# Generated by Django 4.0.5 on 2022-09-26 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0007_remove_user_issued_books_user_issued_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='issued_books',
        ),
        migrations.AddField(
            model_name='book',
            name='members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
