# Generated by Django 4.0.5 on 2022-09-26 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0008_remove_user_issued_books_book_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='issued',
        ),
    ]
