# Generated by Django 4.0.5 on 2022-09-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0009_remove_book_issued'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='members',
            new_name='member',
        ),
    ]
