# Generated by Django 4.0.5 on 2022-10-02 14:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0011_member_delete_user_alter_book_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('action', models.CharField(max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookApp.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BookApp.member')),
            ],
        ),
    ]
