# Generated by Django 4.0.5 on 2022-10-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0012_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fees',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
