# Generated by Django 4.0.5 on 2022-10-10 11:57

import BookApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0020_alter_transaction_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='book',
            field=models.ForeignKey(null=True, on_delete=models.SET(BookApp.models.get_sentinel_book), to='BookApp.book'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='member',
            field=models.ForeignKey(null=True, on_delete=models.SET(BookApp.models.get_sentinel_user), to='BookApp.member'),
        ),
    ]
